services:
  access-control-db:
    image: postgres:15
    environment:
      POSTGRES_DB: access_control_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/init/access:/docker-entrypoint-initdb.d

  catalog-db:
    image: postgres:15
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./db/init/catalog:/docker-entrypoint-initdb.d

  hresources-db:
    image: postgres:15
    environment:
      POSTGRES_DB: hresources_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./db/init/hresources:/docker-entrypoint-initdb.d

  appointment-db:
    image: postgres:15
    environment:
      POSTGRES_DB: appointment_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - ./db/init/appointment:/docker-entrypoint-initdb.d
